# -*- coding: utf-8 -*-
"""exp43a_family_datagen.py -- canonical Q1-bridge family for exp43a.

exp43a representability analysis (design doc 23 "exp43a", commit ef15d76,
criteria FROZEN): canonical story family, K=4, T=5, 6 verbs, 2-hop Q1
bridge questions with swap twins, >= 200 items, generated by the exp41
generator at a fixed seed, V-suite run for the record.

Follows the exp42_c2_datagen precedent exactly: exp41_story_generator is
imported and its module-level inventory/spec constants are rebound for the
run -- the generator file itself is NOT modified. Rebinds:

  * VERBS / SWAP_VERBS -> 6-verb inventory. FLAGGED CHOICE (doc 23 fixes
    the count at 6 but does not name the verbs): the five audited exp41
    verbs (ضرب حمل رفع قطع فتح) plus ساعد as the sixth, so the swap-capable
    pool {ضرب حمل رفع ساعد} has 4 members (Q1 needs v2 drawn from swap
    verbs; 4 gives 4x5=20 ordered (v2,v1) bridge combinations).
  * SPLIT_SPEC -> Q1-only twin pairs at K=(4,4), T=(5,5) in EVERY split.
    The canonical FAMILY for the representability certificate is the
    train split: 100 pairs = 200 items (the doc's >=200 floor). val and
    test_a/b/c splits exist solely so the frozen V-suite (which requires
    >= 500 test items) runs unchanged for the record.

Outputs (new filenames only; frozen exp41/exp42 artifacts untouched):
  stories_exp43a_family.json / stories_exp43a_family_manifest.json
  results_exp43a_validation*.json (validator's own never-overwrite suffix)
"""

import hashlib
import json
from collections import Counter

import exp41_story_generator as gen
import validate_exp41_data as val
import exp42_compiler as comp

SEED = 4301
OUT = "stories_exp43a_family.json"
MANIFEST = "stories_exp43a_family_manifest.json"
VAL_BASE = "results_exp43a_validation"

VERB6 = ["ضرب", "حمل", "رفع", "ساعد", "قطع", "فتح"]

FAMILY_SPEC = {
    "train":  {"Q1": 100, "Q2": 0, "Q0": 0, "K": (4, 4), "T": (5, 5)},
    "val":    {"Q1": 50,  "Q2": 0, "Q0": 0, "K": (4, 4), "T": (5, 5)},
    "test_a": {"Q1": 84,  "Q2": 0, "Q0": 0, "K": (4, 4), "T": (5, 5)},
    "test_b": {"Q1": 84,  "Q2": 0, "Q0": 0, "K": (4, 4), "T": (5, 5)},
    "test_c": {"Q1": 84,  "Q2": 0, "Q0": 0, "K": (4, 4), "T": (5, 5)},
}

FULL_VERBS = dict(gen.VERBS)                              # snapshots
FULL_SPEC = dict(gen.SPLIT_SPEC)


def canonical_sha256(obj):
    payload = json.dumps(obj, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def main():
    assert all(v in FULL_VERBS for v in VERB6), "verb subset outside inventory"
    gen.VERBS = {v: FULL_VERBS[v] for v in VERB6}
    gen.SWAP_VERBS = [v for v, c in gen.VERBS.items() if c["swap"]]
    gen.SPLIT_SPEC = FAMILY_SPEC
    assert len(gen.SWAP_VERBS) >= 2, "family needs >=2 swap verbs for Q1"
    try:
        items, holdout = gen.generate(SEED)
    finally:
        gen.VERBS = dict(FULL_VERBS)                      # restore
        gen.SWAP_VERBS = [v for v, c in gen.VERBS.items() if c["swap"]]
        gen.SPLIT_SPEC = dict(FULL_SPEC)

    # family sanity: every item is a K=4 T=5 Q1 twin-pair member
    assert all(it["qtype"] == "Q1" and it["K"] == 4 and it["T"] == 5
               for it in items), "family constraint violated"
    n_train = sum(it["split"] == "train" for it in items)
    assert n_train >= 200, "family below the pre-registered >=200 floor"

    # every referent must have a frozen exp42 noun embedding
    angles, _emb_meta, emb_sha = comp.load_embeddings()
    missing = {r["name"] for it in items for r in it["referents"]
               if r["name"] not in angles}
    assert not missing, "referents without frozen embeddings: %s" % missing

    sha = canonical_sha256(items)
    counts = Counter((it["split"], it["qtype"]) for it in items)
    split_counts = Counter(it["split"] for it in items)
    meta = {
        "experiment": "exp43a",
        "purpose": "canonical Q1 bridge family for the representability "
                   "certificate (doc 23 exp43a)",
        "design_doc": "qnlp_private_docs/23_exp43_ladder_representability_"
                      "design.md exp43a (commit ef15d76)",
        "seed": SEED,
        "dataset_sha256": sha,
        "n_items": len(items),
        "family_definition": "the train split (%d items = %d twin pairs); "
                             "val/test splits exist only so the frozen "
                             "V-suite can run for the record" %
                             (n_train, n_train // 2),
        "split_counts": dict(split_counts),
        "split_qtype_counts": {"%s/%s" % (s, q): n
                               for (s, q), n in sorted(counts.items())},
        "verb_inventory": {v: {"human_patients": c["human_patients"],
                               "swap": c["swap"], "objects": c["objects"]}
                           for v, c in FULL_VERBS.items() if v in VERB6},
        "humans": gen.HUMANS, "objects": gen.OBJECTS,
        "embeddings_sha256": emb_sha,
        "holdout_verb_argument_pairs": sorted([list(p) for p in holdout]),
        "notes": [
            "generated by exp41_story_generator with module-level rebind "
            "of VERBS/SWAP_VERBS/SPLIT_SPEC (exp42_c2_datagen precedent); "
            "generator file unmodified; frozen main dataset untouched",
            "6-verb inventory: five audited exp41 verbs + ساعد (flagged "
            "choice, doc 23 names the count only)",
            "Q1 bridge twins only, K=4, T=5, every split",
        ],
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump({"meta": meta, "items": items}, f, ensure_ascii=False,
                  indent=1)
    manifest = {k: v for k, v in meta.items() if k != "verb_inventory"}
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=1)

    print("[exp43a-datagen] wrote %s: %d items, sha256=%s"
          % (OUT, len(items), sha))
    for s in FAMILY_SPEC:
        print("  %-8s %5d" % (s, split_counts[s]))

    # V-suite for the record (frozen criteria; validator suffixes output)
    val.DATA = OUT
    val.RESULTS_BASE = VAL_BASE
    print("[exp43a-datagen] running frozen V-suite -> %s*.json" % VAL_BASE)
    rc = val.main()
    print("[exp43a-datagen] V-suite return code: %s" % rc)


if __name__ == "__main__":
    main()
